### ISSUE TITLE
Tracking issues for flutter CLI support

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#17]
Couple of things we need to decide:
- [x] How to pick flutter and Android SDK versions for analysis?
  - [x] Do we do that as part of the pana library, or is it assumed to be done externally?
  - [x] Can/should flutter use the Dart SDK we specify, or are we fine with whatever version it downloads?
  - [x] For how long can we reuse the downloaded stack?

- [x] The third-party dependency involvement here seems to be huge, and we use very little of it. Is there an alternative way to "simulate" flutter's version of `pub get`, without the full flutter stack?

**Comment by mit-mit** [comment]
Flutter doesn't really have versions (yet), so we should rely on the last pushed build in it's [alpha channel](https://github.com/flutter/flutter/tree/alpha).

Not sure I get the Android SDK question.

You must use the Dart SDK vended by Flutter for Flutter packages; if not, we are not doing what the customer is doing.

**Comment by isoos** [comment]
Are you suggesting we shall always analyze on the alpha channel's HEAD?

Flutter requires an Android SDK (any version should do), which seems to be irrelevant for our purposes, but I would like to double-check here.

**Comment by mit-mit** [comment]
Yes, alpha for flutter is similar to stable for Dart SDK; it's where the latest 'known good build' lives.

As for Android, I suggest we use the latest stable Android SDK.

**Comment by kevmoo** [comment]
Sadly, we can't use `alpha` in Docker, because everything runs in `root` and the `alpha` Flutter script errors out if it sees root – post alpha is just prints a warning.

**Comment by kevmoo** [comment]
...well, that was the case when I last looked at alpha. Maybe this has changed...

**Comment by mit-mit** [comment]
That was fixed a few weeks ago:
https://github.com/flutter/flutter/tree/alpha/bin

**Comment by kevmoo** [comment]
Noticed. Awesome.

**Comment by isoos** [comment]
I think all of these were answered:
- Use the latest flutter alpha channel.
- Flutter setup is done externally, and it is easy because we don't need the Android SDK.
